"""create assets

Revision ID: 5a19fdb84cce
Revises: d3377ed8e6d7
Create Date: 2025-09-09 12:57:07.648084

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5a19fdb84cce"
down_revision: str | Sequence[str] | None = "d3377ed8e6d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
