"""create assets

Revision ID: d3377ed8e6d7
Revises: 149573347043
Create Date: 2025-09-09 12:55:00.976918

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d3377ed8e6d7"
down_revision: str | Sequence[str] | None = "149573347043"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
